FROM node:16-alpine

ENV MONGO_DB_USERNAME=admin \
    MONGO_DB_PASSWORD=password 

RUN mkdir -p /home/app
WORKDIR /home/app

COPY ./app/package.json .
RUN npm install
COPY ./app .

CMD [ "node", "server.js" ]