version: '3.1'

services:

  my-app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports: 
      - 3000:3000
    networks:
      - test
    volumes:
    - ./app/node_modules
    - ./app:/app
  mongo:
    image: mongo
    restart: always
    ports: 
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - test

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
    networks:
      - test

networks:
  test:

