version: '3'
services:
  redis-server:
    build: 
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
  node-app:
    restart: always
    build: 
      context: ./node-app
      dockerfile: Dockerfile
    ports:
      - 4201:4201